name: space_id
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  camera: ^0.11.1
  permission_handler: ^12.0.1

flutter:
  uses-material-design: true
